routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('persons', 'PersonsController')->except(['show']);
//Illuminate\Routing\Router::class;
//dd(Route::getFacadeRoot());

app/Models/PersonModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PersonModel extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */

    
    protected $table = 'persons';
    protected $fillable = [ 'id', 'username', 'email', 'website', 'description' ];

    public $timestamps = true;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PersonsController.php
<?php

namespace App\Http\Controllers;

use App\Models\PersonModel;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/**
 * @referencia
 * 		https://laravel.com/docs/5.3/controllers#resource-controllers
 */
class PersonsController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$data = PersonModel::latest()->paginate(10);
		// return view('persons.index',compact('data'))->with('i', (request()->input('page', 1) - 1) * 5);
    return response()->json($data);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		// return view('persons.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$request->validate([
			'username' => 'required',
			'email' => 'required',
		]);

		PersonModel::create($request->all());
		// return redirect()->route('persons.index')->with('success', 'Usuário adicionado com sucesso.');

    $data = array(
      'status'  => 'success',
      'message' => 'Usuário adicionado com sucesso.'
    );
    return response()->json($data);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  \App\Models\PersonModel  $personModel
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		$person = PersonModel::find($id);
		return view('persons.edit', compact('person'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \App\Models\PersonModel  $personModel
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		$request->validate([
			'username' => 'required',
			'email' => 'required',
		]);

		$person = PersonModel::find($id)->update($request->all());
		// return redirect()->route('persons.index')->with('success', 'Usuário atualizado com sucesso.');

    $data = array(
      'status'  => 'success',
      'message' => 'Usuário atualizado com sucesso.'
    );
    return response()->json($data);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  \App\Models\PersonModel  $personModel
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		$person = PersonModel::find($id)->delete();
		// return redirect()->route('persons.index')->with('success', 'Usuário deletado com sucesso.');

    $data = array(
      'status'  => 'success',
      'message' => 'Usuário deletado com sucesso.'
    );
    return response()->json($data);
	}

}

resources/views/_partials/head.blade.php
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">

	<title>Acordo Online</title>

  <link rel="icon" href="https://acordoonline.com/sobre/wp-content/uploads/2017/08/fav32.png" sizes="32x32">
  <link rel="shortcut icon" href="https://acordoonline.com/sobre/wp-content/uploads/2017/08/fav32.png">
  <link rel="apple-touch-icon" href="https://acordoonline.com/sobre/wp-content/uploads/2017/08/fav57.png" sizes="57x57">
  <link rel="apple-touch-icon" href="https://acordoonline.com/sobre/wp-content/uploads/2017/08/fav76.png" sizes="76x76">
  <link rel="apple-touch-icon" href="https://acordoonline.com/sobre/wp-content/uploads/2017/08/fav120.png" sizes="120x120">
  <link rel="apple-touch-icon" href="https://acordoonline.com/sobre/wp-content/uploads/2017/08/fav152.png" sizes="114x114">

	<!-- Fonts -->
	<link href="//fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

	<!-- bootstrap -->
	<link href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet" >
	<link href="//cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<script src="//cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

resources/views/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
		@include('_partials.head')
    </head>
    <body>

		<main class="container">

			<!-- Header -->
      <div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
        <i class="bi bi-person-bounding-box mx-2"></i>
        <div class="lh-1">
          <h1 class="h6 mb-0 text-white lh-1">AO - Person Test</h1>
        </div>
      </div>

			<div id="app"></div>
		</main>

    <script src="js/app.js"></script>
  </body>
</html>

resources/views/persons/_header.blade.php
<!-- Header -->
<div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
	<i class="bi bi-person-bounding-box mx-2"></i>
	<div class="lh-1">
		<h1 class="h6 mb-0 text-white lh-1">AO - Person Test</h1>
	</div>
</div>

resources/views/persons/create.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
		@include('_partials.head')
    </head>
    <body>

		<main class="container">

			@include('persons._header')

			@if ($errors->any())
				<div class="alert alert-danger" role="alert">
					<p><strong>Ops!</strong> Algo deu errado...</p>
					<ul>
						@foreach ($errors->all() as $error)
								<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif

			<!-- Person List-->
			<div class="my-3 p-3 bg-body rounded shadow-sm">
				<h6 class="border-bottom pb-2 mb-0">Adcionar</h6>
        
				<!-- Formulário --> 
				<form action="{{ route('persons.store') }}" method="POST">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">

					<div class="lh-sm border-bottom mb-3">

						<div class="mb-3">
							<label for="username" class="form-label">Usuário</label>
							<div class="input-group mb-3">
								<span class="input-group-text" id="basic-addon1">@</span>
								<input type="text" class="form-control" name="username" id="username" aria-describedby="username-help">
							</div>
							<div id="username-help" class="form-text">Nome do usuário.</div>
						</div>

					</div>

					<div class="lh-sm border-bottom mb-3">
						<div class="mb-3">
							<label for="email" class="form-label">E-mail</label>
							<div class="input-group mb-3">
								<input type="email" class="form-control" name="email" id="email" aria-describedby="email-help">
							</div>
							<div id="email-help" class="form-text">E-mail do usuário.</div>
						</div>
					</div>

					<div class="lh-sm border-bottom mb-3">
						<div class="mb-3">
							<label for="website" class="form-label">Website</label>
							<div class="input-group mb-3">
								<input type="text" class="form-control" name="website" id="website" aria-describedby="website-help">
							</div>
							<div id="website-help" class="form-text">Website do usuário.</div>
						</div>
					</div>

					<div class="lh-sm border-bottom mb-3">
						<div class="mb-3">
							<label for="description" class="form-label">Descrição</label>
							<div class="input-group mb-3">
								<textarea class="form-control" name="description" id="description" cols="30" rows="10" aria-describedby="description-help"></textarea>
							</div>
							<div id="description-help" class="form-text">Breve descrição do usuário.</div>
						</div>
					</div>

					<div class="text-end">
						<button type="submit" class="btn btn-sm btn-primary">Salvar Alterações</button>
					</div>
				</form>

			</div>
		</main>
	</body>
</html>

resources/views/persons/edit.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
		@include('_partials.head')
    </head>
    <body>

		<main class="container">

			@include('persons._header')

			@if ($errors->any())
				<div class="alert alert-danger" role="alert">
					<p><strong>Ops!</strong> Algo deu errado...</p>
					<ul>
						@foreach ($errors->all() as $error)
								<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif

			<!-- Person List-->
			<div class="my-3 p-3 bg-body rounded shadow-sm">
				<h6 class="border-bottom pb-2 mb-0">Editar</h6>

				@if(empty($person))
					<p>Houve algum erro ao carregar as informações. Tente novamente.</p>
				@else

					<!-- Formulário --> 
					<form action="{{ route('persons.update', $person->id) }}" method="POST">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						{{ method_field('PUT')}}
						
						<div class="lh-sm border-bottom mb-3">

							<div class="mb-3">
								<label for="username" class="form-label">Usuário</label>
								<div class="input-group mb-3">
									<span class="input-group-text" id="basic-addon1">@</span>
									<input type="text" class="form-control" name="username" id="username" aria-describedby="username-help" value="{{ $person['username'] }}">
								</div>
								<div id="username-help" class="form-text">Nome do usuário.</div>
							</div>

						</div>

						<div class="lh-sm border-bottom mb-3">
							<div class="mb-3">
								<label for="email" class="form-label">E-mail</label>
								<div class="input-group mb-3">
									<input type="email" class="form-control" name="email" id="email" aria-describedby="email-help" value="{{ $person->email }}">
								</div>
								<div id="email-help" class="form-text">E-mail do usuário.</div>
							</div>
						</div>

						<div class="lh-sm border-bottom mb-3">
							<div class="mb-3">
								<label for="website" class="form-label">Website</label>
								<div class="input-group mb-3">
									<input type="text" class="form-control" name="website" id="website" aria-describedby="website-help" value="{{ $person->website }}">
								</div>
								<div id="website-help" class="form-text">Website do usuário.</div>
							</div>
						</div>

						<div class="lh-sm border-bottom mb-3">
							<div class="mb-3">
								<label for="description" class="form-label">Descrição</label>
								<div class="input-group mb-3">
									<textarea class="form-control" name="description" id="description" cols="30" rows="10" aria-describedby="description-help">{{ $person->description }}</textarea>
								</div>
								<div id="description-help" class="form-text">Breve descrição do usuário.</div>
							</div>
						</div>

						<div class="text-end">
							<button type="submit" class="btn btn-sm btn-primary">Salvar Alterações</button>
						</div>
					</form>
				@endif

			</div>
		</main>
	</body>
</html>

resources/views/persons/form.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
		@include('_partials.head')
    </head>
    <body>

		<main class="container">

			@include('persons._header')

			@if ($errors->any())
				<div class="alert alert-danger" role="alert">
					<p><strong>Ops!</strong> Algo deu errado...</p>
					<ul>
						@foreach ($errors->all() as $error)
								<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif

			<!-- Person List-->
			<div class="my-3 p-3 bg-body rounded shadow-sm">
				<h6 class="border-bottom pb-2 mb-0">[[ Adcionar ou Editar ]]</h6>

				<!-- Formulário --> 
				<form action="{{ route('persons.store') }}" method="POST">
					
					<div class="lh-sm border-bottom mb-3">

						<div class="mb-3">
							<label for="username" class="form-label">Usuário</label>
							<div class="input-group mb-3">
								<span class="input-group-text" id="basic-addon1">@</span>
								<input type="text" class="form-control" name="username" id="username" aria-describedby="username-help">
							</div>
							<div id="username-help" class="form-text">Nome do usuário.</div>
						</div>

					</div>

					<div class="lh-sm border-bottom mb-3">
						<div class="mb-3">
							<label for="email" class="form-label">E-mail</label>
							<div class="input-group mb-3">
								<input type="email" class="form-control" name="email" id="email" aria-describedby="email-help">
							</div>
							<div id="email-help" class="form-text">E-mail do usuário.</div>
						</div>
					</div>

					<div class="lh-sm border-bottom mb-3">
						<div class="mb-3">
							<label for="website" class="form-label">Website</label>
							<div class="input-group mb-3">
								<input type="text" class="form-control" name="website" id="website" aria-describedby="website-help">
							</div>
							<div id="website-help" class="form-text">Website do usuário.</div>
						</div>
					</div>

					<div class="lh-sm border-bottom mb-3">
						<div class="mb-3">
							<label for="description" class="form-label">Descrição</label>
							<div class="input-group mb-3">
								<textarea class="form-control" name="description" id="description" cols="30" rows="10" aria-describedby="description-help"></textarea>
							</div>
							<div id="description-help" class="form-text">Breve descrição do usuário.</div>
						</div>
					</div>

					<div class="text-end">
						<button type="submit" class="btn btn-sm btn-primary">Salvar Alterações</button>
					</div>
				</form>

			</div>
		</main>
	</body>
</html>

resources/views/persons/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
		@include('_partials.head')
    </head>
    <body>

		<main class="container">

			@include('persons._header')

			@if ($message = Session::get('success'))
				<div class="alert alert-success" role="alert">
					<p>{{ $message }}</p>
				</div>
			@endif

			<!-- Person List-->
			<div class="my-3 p-3 bg-body rounded shadow-sm">
				<h6 class="border-bottom pb-2 mb-0">Cadastros</h6>

				<!--
					Lista de pessoas cadastradas
				-->

				@if(empty($data))
					<p>Nenhum cadastro encontrado em nossa base de dados. <a href="{{ route('persons.create') }}">Clique aqui</a> e comece o cadastro agora mesmo!</p>
				@else

					@foreach ( $data as $key => $user )
					<div class="lh-sm border-bottom">
						<div class="d-flex text-muted pt-3">
							<img class="flex-shrink-0 me-2 rounded" src="//via.placeholder.com/32x32.png?text=AO" width="32" height="32" />

							<p class="pb-3 mb-0 small">
								<a href="{{ route('persons.edit', $user->id) }}"><strong class="d-block text-gray-dark">{{ '@' . $user->username }} &lt;{{ $user->email }}&gt;</strong></a>
								{{ $user->description }}
							</p>

						</div>
						<div class="text-muted pt-1">

							<form action="{{ route('persons.destroy',$user->id) }}" method="POST" class="small text-end">
								<input type="hidden" name="_token" value="{{ csrf_token() }}">
								<input name="_method" type="hidden" value="DELETE">
								{{ $user->created_at->format('d/m/Y') }} |
								<button class="btn btn-sm btn-danger" type="submit"><i class="bi bi-trash small"></i></button>
							</form>

						</div>
					</div>
					@endforeach
				@endif

				<div class="d-flex justify-content-between mt-3">
					<div></div>
					<div>
						<small class="text-muted text-center">{!! $data->links() !!}</small>
					</div>
					<small class="text-end">
						<a href="{{ route('persons.create') }}">Adicionar</a>
					</small>
				</div>

			</div>

		</main>

    </body>
</html>